Update bot

diff --git a/bot b/bot
--- a/bot
+++ b/bot
@@ -220,49 +220,53 @@ printf "%s\n\e[0;39;49m"
 }
 ## MAIN ------------------------------------------------------------------------
 # Make sure this script run inside Bot directory
-cd "$THIS_DIR" || exit
-case $1 in
-  update)
-    update
-  ;;
-  create)
-    create
-  ;;
-  install)
-    install
-  ;;
-  fix)
-    fix
-  ;;
-  autolaunch)
-    autolaunch
-  ;;
-  help)
-    usage
-  ;;
-  createmanual)
-    createmanual
-  ;;
-  a*)
-    id="${1/a/}"
-    if [ -a "$THIS_DIR"/bot-"$id".lua ]; then
-      screen -x -s bot-"$id" quit
-      while true ; do
-        screen -s bot-"$id" ./telegram-cli -p bot-"$id" -s bot-"$id".lua
-        sleep 10
-      done
-    else
-      usage
-    fi
-  ;;
-  clr)
-    clear
-  ;;
-  *)
-    if [ -a "$THIS_DIR"/bot-"$1".lua ]; then
-      ./telegram-cli -p bot-"$1" -s bot-"$1".lua
-    else
-    usage
-    fi
-  ;;
-esac
+
+#!/usr/bin/env bash
+
+THIS_DIR=$(cd $(dirname $0); pwd)
+cd $THIS_DIR
+
+update() {
+  git pull
+  git submodule update --init --recursive
+}
+
+install() {
+  git pull
+  git submodule update --init --recursive
+  patch -i "patches/disable-python-and-libjansson.patch" -p 0 --batch --forward
+  RET=$?;
+  git clone --recursive https://github.com/janlou/tg.git
+  cd tg
+  if [ $RET -ne 0 ]; then
+    autoconf -i
+  fi
+  ./configure && make
+
+  RET=$?; if [ $RET -ne 0 ]; then
+    echo "Error. Exiting."; exit $RET;
+  fi
+  cd ..
+}
+
+if [ "$1" = "install" ]; then
+  install
+elif [ "$1" = "update" ]; then
+  update
+else
+  if [ ! -f ./tg/telegram.h ]; then
+    echo "tg not found"
+    echo "Run $0 install"
+    exit 1
+  fi
+
+  if [ ! -f ./tg/bin/telegram-cli ]; then
+    echo "tg binary not found"
+    echo "Run $0 install"
+    exit 1
+  fi
+  while true; do
+    rm -r ../.telegram-cli/state #Prevent tg from crash
+    ./tg/bin/telegram-cli -k ./tg/tg-server.pub -s ./bot/bot.lua -l 1 -E $@
+  done
+fi
